version = 0.1
[default.deploy.parameters]
stack_name = "sysn24-app"
resolve_s3 = true
s3_prefix = "sysn24-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "RoleArn=\"arn:aws:iam::675778140370:role/LabRole\""
image_repositories = []
