AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for SySN24

Parameters:
  RoleARN:
    Type: String
    Default: arn:aws:iam::208497263506:role/LabRole
    Description: ARN del rol que usarán las funciones Lambda

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'Content-Type, X-Amz-Date, Authorization, X-Api-Key, X-Requested-With'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"

  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/getProducts/app.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Role: !Ref RoleARN
      Policies:
        - DynamoDBReadPolicy:
            TableName: Products
      Environment:
        Variables:
          TABLE_NAME: Products
      Events:
        GetProductsAPI:
          Type: Api
          Properties:
            Path: /products
            Method: GET
            RestApiId: !Ref ApiGatewayApi

  InsertProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/insertProducts/app.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Role: !Ref RoleARN
      Policies:
        - DynamoDBReadPolicy:
            TableName: Products
      Environment:
        Variables:
          TABLE_NAME: Products
      Events:
        InsertProductsAPI:
          Type: Api
          Properties:
            Path: /products
            Method: POST
            RestApiId: !Ref ApiGatewayApi

  BuyProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/postBuy/app.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Role: !Ref RoleARN
      Policies:
        - DynamoDBReadPolicy:
            TableName: Products
        - DynamoDBWritePolicy:
            TableName: Orders
        - S3WritePolicy:
            BucketName: !Ref PDFStorageBucket
      Environment:
        Variables:
          TABLE_NAME: Products
          PDF_BUCKET: !Ref PDFStorageBucket
          ORDERS_TABLE_NAME: Orders
      Events:
        BuyProductsAPI:
          Type: Api
          Properties:
            Path: /buy
            Method: POST
            RestApiId: !Ref ApiGatewayApi

  SendTicketFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/sendTicket/app.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Role: !Ref RoleARN
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref PDFStorageBucket
        - SNSPublishMessagePolicy:
            TopicName: PDFTopic
        - Statement:
            Effect: Allow
            Action: s3:PutBucketNotification
            Resource: !Sub "arn:aws:s3:::${PDFStorageBucket}"
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref PDFTopic
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket: !Ref PDFStorageBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .pdf

  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Products
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Orders
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  PDFStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sy24-pdf-storage
      AccessControl: Private

  PDFTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: PDFTopic
